feat: add advanced encoder options `Config`
rust-embedded/svd pull request #207
Opened 2022-07-14 15:34 UTC by duskmoon314

- Add `convert_case` to dependencies
- Add advanced encoder options `Config`

BREAKING CHANGE
- `Encode` trait needs to implement `encode_with_config`

2022-07-15 07:34 UTC, burrbull commented
Looks good in first view.
Could you also add/modify some tests in `tests` directory?

2022-07-15 08:11 UTC, duskmoon314 commented
Ok, I will add some tests ASAP.

2022-07-15 09:22 UTC, duskmoon314 commented
I add some simple tests to show the usage of `svd_encoder::Config`

It's good to add tests for all options but needs more work. orz

2022-07-15 10:10 UTC, burrbull commented on svd-encoder/src/config.rs
> +    UpperSnake,
Here http://calebmer.com/inflections/inflections/case/index.html
it is called "constant case"

2022-07-16 01:17 UTC, duskmoon314 commented
- rename `UpperSnake` to `Constant`
- add tests in all files that are included in `tests/lib.rs`

2022-07-16 08:56 UTC, burrbull submitted a review, later dismissed

2022-07-16 09:41 UTC, burrbull commented
cc @Emilgardis any comments?

2022-07-16 12:46 UTC, Emilgardis requested changes
awesome!

missing a optional serialize/deserialize for `Config`, but that's not super important and not a blocker (would just be nice to have to enable some kind of config file in higher level crate).

2022-07-16 12:46 UTC, Emilgardis commented on tests/src/lib.rs
> +) {
I think `run_test` should use this function, so to not duplicate code

2022-07-16 13:01 UTC, duskmoon314 commented
> missing a optional serialize/deserialize

There is no serialize/deserialize for `svd_parser::Config`, so I think it's unnecessary. `svd_encoder::Config` has many fields so it might be beneficial in use. Now I declare an `update` method to set config, and this is the way I use in the temptation of implementing the `format` feature in svdtools.

> I think `run_test` should use this function

Sure. Will fix this soon.

2022-07-16 13:16 UTC, duskmoon314 commented
Change `run_test` to:

```rust
pub fn run_test<
    T: Parse<Error = SVDErrorAt, Object = T, Config = Config>
        + Encode<Error = EncodeError>
        + core::fmt::Debug
        + PartialEq,
>(
    // tests: [(Object, input string, output string)],
    tests: &[(T, &str, &str)],
    parser_config: Option<Config>,
    encoder_config: Option<svd_encoder::Config>,
)
```

Change all tests using `run_test` (Keep most of them, add several tests for config)

2022-07-16 13:27 UTC, Emilgardis commented
> There is no serialize/deserialize for `svd_parser::Config`, so I think it's unnecessary.

Indeed, just saying it's something we should maybe look into :D 

Regarding the `run_test`, I think it's worth having them as two separate functions, and `run_test` calls `runs_test_with_config`.

For that to work `run_test_with_config` should probably take a iterator instead..

However, I'm fine with this.

2022-07-16 13:29 UTC, Emilgardis approved these changes
awesome job, thanks a lot!

one minor issue/non-issue with `run_test`, but it's not a problem

2022-07-16 13:31 UTC, duskmoon314 commented
> Regarding the `run_test`, I think it's worth having them as two separate functions, and `run_test` calls `runs_test_with_config`.
> 
> For that to work `run_test_with_config` should probably take a iterator instead..

Oh, you are right. That way is more simple to use. I need to think about how to do this.

2022-07-18 04:54 UTC, burrbull approved these changes

2022-07-18 04:55 UTC, burrbull commented
Lets merge this. @duskmoon314 if you have more improvements, please open new PR.
bors r+

2022-07-18 04:57 UTC, merged